 /* Font Body */ @font-face{font-family: 'Noto Sans';font-style: italic;font-weight: 400;font-display: swap;src: url(https://fonts.gstatic.com/s/notosans/v11/o-0OIpQlx3QUlC5A4PNr4ARMQ_m87A.woff2) format('woff2'), url(https://fonts.gstatic.com/s/notosans/v11/o-0OIpQlx3QUlC5A4PNr4DRG.woff) format('woff')} @font-face{font-family: 'Noto Sans';font-style: italic;font-weight: 700;font-display: swap;src: url(https://fonts.gstatic.com/s/notosans/v11/o-0TIpQlx3QUlC5A4PNr4Az5ZuyDzW0.woff2) format('woff2'), url(https://fonts.gstatic.com/s/notosans/v11/o-0TIpQlx3QUlC5A4PNr4Az5ZtyH.woff) format('woff')} @font-face{font-family: 'Noto Sans';font-style: normal;font-weight: 400;font-display: swap;src: url(https://fonts.gstatic.com/s/notosans/v11/o-0IIpQlx3QUlC5A4PNr5TRA.woff2) format('woff2'), url(https://fonts.gstatic.com/s/notosans/v11/o-0IIpQlx3QUlC5A4PNb4Q.woff) format('woff')} @font-face{font-family: 'Noto Sans';font-style: normal;font-weight: 700;font-display: swap;src: url(https://fonts.gstatic.com/s/notosans/v11/o-0NIpQlx3QUlC5A4PNjXhFVZNyB.woff2) format('woff2'), url(https://fonts.gstatic.com/s/notosans/v11/o-0NIpQlx3QUlC5A4PNjXhFlYA.woff) format('woff')} body{background-color:#1e1e1e} h1, h2, h3, h4, h5, h6{border-bottom:1px solid #97999A;margin:0;color:#fefefe;font-weight:700;font-family:'Noto Sans', sans-serif ;} p{color:#fefefe;font-weight:400;font-family:'Noto Sans', sans-serif ;opacity:.8;margin-top:12px;} body{padding: 25px} .button{display:inline-flex;align-items:center; margin:12px 12px 12px 0;padding:10px 15px;outline:0;border:0; border-radius:10px;line-height:20px; color:#fefefe; background-color:#00AD73; font-size:13px;white-space:nowrap;overflow:hidden;} .button:hover{opacity:.6} 	 .scrollImage{display:flex;flex-wrap:wrap;align-items:flex-start;justify-content:center; margin:2em 0; position:relative;left:-7.5px; width:calc(100% + 15px)} .scrollImage > *{border-radius:10px;width:calc(33.333% - 15px); margin:0 7.5px 15px} .scrollImage{flex-wrap:nowrap;justify-content:flex-start;position:relative;width:calc(100% + 0px);left:-20px;padding:0 20px; overflow-y:hidden;overflow-x:scroll;scroll-behavior:smooth;scroll-snap-type:x mandatory; -ms-overflow-style:none;-webkit-overflow-scrolling:touch} .scrollImage > *{display:block;flex-shrink:0; width:80%; margin:0 15px 0 0; scroll-snap-align:center} .scrollImage > *:last-child{margin-right:0} .scrollImage:after{content:'';display:block;flex-shrink:0; align-self:stretch;padding-left:20px} 

Halo!

Geser gambarnya sayang :)

￼ ￼ ￼ ￼ ￼ ￼ ￼ 

flag=1 function f1(){ alert("Terima kasih banyakkkkkk><") <!-- Ganti NOMOR 62887435095568 dengan NO WA KAMU --> window.location = "https://api.whatsapp.com/send?phone=+62887435095568&text=Hai,%0AAku udah bacain semuanya:(%0A%0AAku%20mau%20kok%20terima%20kamu><"; } function f(){ 	alert("Menyedihkan:(") 	alert("Ya tapi gkppaa deh:)") 	alert("Sehat selalu yaa~") 	alert("Semoga harimu indah~") 	alert("I love U") } 
